#!/bin/bash

[[ -a /var/log/messages ]] && file=/var/log/messages
[[ -a /var/log/dmesg ]] && file=/var/log/dmesg

val=$(sudo grep 'tsc:.*cal' $file | grep 'tsc:' | tail -1  | sed 's/.*: //g' | cut -d' ' -f1)
echo -e "scale=4\n$val * 1000"  | bc
