/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tsc_tsclog */

#ifndef _Included_tsc_tsclog
#define _Included_tsc_tsclog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tsc_tsclog
 * Method:    availcpus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tsc_tsclog_availcpus
  (JNIEnv *, jclass);

/*
 * Class:     tsc_tsclog
 * Method:    cpu
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tsc_tsclog_cpu
  (JNIEnv *, jclass);

/*
 * Class:     tsc_tsclog
 * Method:    tid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tsc_tsclog_tid
  (JNIEnv *, jclass);

/*
 * Class:     tsc_tsclog
 * Method:    pin
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_tsc_tsclog_pin
  (JNIEnv *, jclass, jint);

/*
 * Class:     tsc_tsclog
 * Method:    now
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tsc_tsclog_now
  (JNIEnv *, jclass);

/*
 * Class:     tsc_tsclog
 * Method:    stdout_now
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tsc_tsclog_stdout_1now
  (JNIEnv *, jclass);

/*
 * Class:     tsc_tsclog
 * Method:    stdout_label_now
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_tsc_tsclog_stdout_1label_1now
  (JNIEnv *, jclass, jstring);

/*
 * Class:     tsc_tsclog
 * Method:    stderr_now
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tsc_tsclog_stderr_1now
  (JNIEnv *, jclass);

/*
 * Class:     tsc_tsclog
 * Method:    stderr_label_now
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_tsc_tsclog_stderr_1label_1now
  (JNIEnv *, jclass, jstring);

/*
 * Class:     tsc_tsclog
 * Method:    mklog
 * Signature: (Ljava/lang/String;JIIILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_tsc_tsclog_mklog
  (JNIEnv *, jclass, jstring, jlong, jint, jint, jint, jstring);

/*
 * Class:     tsc_tsclog
 * Method:    log
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_tsc_tsclog_log
  (JNIEnv *, jclass, jlong);

/*
 * Class:     tsc_tsclog
 * Method:    log1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_tsc_tsclog_log1
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
